<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Import Category')?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Submit  form</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <?php //echo $this->getRequest()->getControllerName();
	$url = Mage::helper("adminhtml")->getUrl('*/*/post'); ?>
<h4>Upload Your CSV File Here</h4>

<form id="edit_form" name="edit_form" action="<?php echo $url;?>" method="post" enctype="multipart/form-data">
    <p><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /></p>
    <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Please upload 1000 Records at a time')?> <span class="required">*</span></td>
				
                    <td class="input-ele"><input class="input-text required-entry" type="file" name="docname" /></td>
                </tr>
            </table>
        </fieldset>
</form>

</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>

