
             

<form action="<?php echo Mage::getUrl('test/index/save') ?>" method="post">
  <fieldset>
    <ul>
     <li>
       <label for="username">Name</label>
       <input type="text" id="username" name="username" />
     </li>
     <li>
         <label for="email">Email</label>
         <input type="text" id="email" name="email" />
     </li>
     <li>
        <label for="address">Address</label>
        <input type="text" id="address" name="address" />
    </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>
