<?php

$data = $this->methodblock2();
?>
             

<form action="<?php echo Mage::getUrl('test/index/edit') ?>" method="post">
  <fieldset>
    <ul>
     <li>
	 <input type="hidden" id="id" value="<?php echo $data->getData('id')   ?>" name="id" />
       <label for="username">Name</label>
       <input type="text" id="username" value="<?php echo $data->getData('username')   ?>" name="username" />
     </li>
     <li>
         <label for="email">Email</label>
         <input type="text" value="<?php echo $data->getData('email')   ?>"  id="email" name="email" />
     </li>
     <li>
        <label for="address">Address</label>
        <input type="text" value="<?php echo $data->getData('address')   ?>"  id="address" name="address" />
    </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>
